spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  h2:
    console.enabled: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
jdbc:
  master:
    url: jdbc:mysql://localhost:3306/bantads-write
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  slave:
    url: jdbc:mysql://localhost:3307/bantads-read
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver